spring:
  data:
    mongodb:
      host: ${mongo_host:localhost}
      # port: 27017
      port: 5801
      username: db_user
      password: Wzj_mysql01
      repositories:
        type: auto
      authentication-database: admin
      database: plugins
      auto-index-creation: true  # auto create index for @Indexed annotation
#      uri: mongodb://db_user:Wzj_mysql01@localhost:27017/coolie-service