version: '2'
services:
  mongo:
    image: mongo
#    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_user
      MONGO_INITDB_ROOT_PASSWORD: Wzj_mysql01
    volumes:
#      - '/root/Desktop/backup/mongodb:/data/db'
      - '/home/jujucom/Desktop/backup/mongodb:/data/db'
    ports:
      - '5801:27017'

#  admin-mongo:
#    image: mrvautin/adminmongo
    # restart: always
#    ports:
#      - '5803:1234'