
## query all group info objects
GET http://localhost:8081/plugin-manager/plugin-groups
Accept: application/json

## get a specific group document
###
GET http://localhost:8081/plugin-manager/plugin-groups/6036472b83a2283cf48b66d7
Accept: application/json

## delete a specific group document
###
DELETE http://localhost:8081/plugin-manager/plugin-groups/6036472b83a2283cf48b66d7
Accept: application/json

## create a group document
###
POST http://localhost:8081/plugin-manager/plugin-groups
Content-Type: application/json

{
  "name": "group4",
  "description": "a test pluginDocument group"
}

###

## update a group document
###
PUT http://localhost:8081/plugin-manager/plugin-groups/6036472b83a2283cf48b66d7
Content-Type: application/json

{
  "id": "6036472b83a2283cf48b66d7",
  "name": "group1",
  "description": "updated group"
}

###

## delete all group documents
###
DELETE http://localhost:8081/plugin-manager/plugin-groups
Content-Type: application/json

###

## create a plugin
POST http://localhost:8081/plugin-manager/plugin-groups/6036472b83a2283cf48b66d7/plugins
Content-Type: application/json

{
  "name": "plugin-2",
  "description": "plugin desc",
  "provider": "WZJ Tech",
  "projectUrl": "/localhost/plugin-2"
}

###