
## query all group info objects
GET http://localhost:8081/plugin-manager/plugin-groups
Accept: application/json

## get a specific group document
###
GET http://localhost:8081/plugin-manager/plugin-groups/6041ab1cf80ffd1e6a0ea781
Accept: application/json

## delete a specific group document
###
DELETE http://localhost:8081/plugin-manager/plugin-groups/6041ab1cf80ffd1e6a0ea781
Accept: application/json

## create a group document
###
POST http://localhost:8081/plugin-manager/plugin-groups
Content-Type: application/json

{
  "name": "group2",
  "description": "a test pluginDocument group4"
}

###

## update a group document
###
PUT http://localhost:8081/plugin-manager/plugin-groups/6041ab1cf80ffd1e6a0ea781
Content-Type: application/json

{
  "id": "6041ab1cf80ffd1e6a0ea781",
  "name": "group1",
  "description": "updated group"
}

###

## delete all group documents
###
DELETE http://localhost:8081/plugin-manager/plugin-groups
Content-Type: application/json

###

## create a plugin
POST http://localhost:8081/plugin-manager/plugin-groups/6041ab1cf80ffd1e6a0ea781/plugins
Content-Type: application/json

{
  "name": "plugin-1",
  "description": "plugin desc",
  "provider": "WZJ Tech",
  "projectUrl": "/localhost/plugin-1"
}

###

## update a plugin
PUT http://localhost:8081/plugin-manager/plugin-groups/6041ab1cf80ffd1e6a0ea781/plugins/plugin-1
Content-Type: application/json

{
  "name": "plugin-2",
  "description": "plugin updated",
  "provider": "WZJ Tech updated",
  "projectUrl": "/localhost/plugin-2.1"
}

###

## delete a plugin
DELETE http://localhost:8081/plugin-manager/plugin-groups/6041ab1cf80ffd1e6a0ea781/plugins/plugin-2
Content-Type: application/json

###

## create a plugin version
POST http://localhost:8081/plugin-manager/plugin-groups/6041ab1cf80ffd1e6a0ea781/plugins/plugin-1/versions
Content-Type: application/json

{
  "version": "0.4.0",
  "date": "2019-08-14T12:17:47Z",
  "requires": null,
  "url": "/version-0.1.0",
  "sha512sum": null
}

###

## delete a plugin version
DELETE http://localhost:8081/plugin-manager/plugin-groups/6041ab1cf80ffd1e6a0ea781/plugins/plugin-1/versions/0.1.0
Content-Type: application/json


###