
## query all group info objects
GET http://localhost:8081/plugin-manager/plugin-groups
Accept: application/json

## get a specific group document
###
GET http://localhost:8081/plugin-manager/plugin-groups/60374d076aaf7f1ae552465b
Accept: application/json

## delete a specific group document
###
DELETE http://localhost:8081/plugin-manager/plugin-groups/60374d076aaf7f1ae552465b
Accept: application/json

## create a group document
###
POST http://localhost:8081/plugin-manager/plugin-groups
Content-Type: application/json

{
  "name": "group1",
  "description": "a test pluginDocument group"
}

###

## update a group document
###
PUT http://localhost:8081/plugin-manager/plugin-groups/60374d076aaf7f1ae552465b
Content-Type: application/json

{
  "id": "60374d076aaf7f1ae552465b",
  "name": "group1",
  "description": "updated group"
}

###

## delete all group documents
###
DELETE http://localhost:8081/plugin-manager/plugin-groups
Content-Type: application/json

###

## create a plugin
POST http://localhost:8081/plugin-manager/plugin-groups/60374d076aaf7f1ae552465b/plugins
Content-Type: application/json

{
  "name": "plugin-1",
  "description": "plugin desc",
  "provider": "WZJ Tech",
  "projectUrl": "/localhost/plugin-1"
}

###

## update a plugin
PUT http://localhost:8081/plugin-manager/plugin-groups/60374d076aaf7f1ae552465b/plugins/plugin-1.1
Content-Type: application/json

{
  "name": "plugin-2",
  "description": "plugin updated",
  "provider": "WZJ Tech updated",
  "projectUrl": "/localhost/plugin-2"
}